# Generated by Django 4.2 on 2023-06-12 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, verbose_name="Наименование района"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Районы",
                "verbose_name_plural": "Районы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Ats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, verbose_name="Наименование АТС"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ats.area",
                        verbose_name="Район",
                    ),
                ),
            ],
            options={
                "verbose_name": "АТС",
                "verbose_name_plural": "АТС",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Cable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sl",
                    models.CharField(max_length=7, verbose_name="Соединительная линия"),
                ),
                (
                    "direction",
                    models.CharField(max_length=40, verbose_name="Направление КЛС"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
                (
                    "tag",
                    models.CharField(max_length=40, verbose_name="Бирка на кабеле"),
                ),
                (
                    "grounding",
                    models.BooleanField(blank=True, verbose_name="Наличие заземления"),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "ats",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ats.ats",
                        verbose_name="АТС",
                    ),
                ),
            ],
            options={
                "verbose_name": "КЛС",
                "verbose_name_plural": "КЛС",
                "ordering": ["direction"],
            },
        ),
        migrations.CreateModel(
            name="Cross",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=3, verbose_name="№ кросса")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
                (
                    "tag",
                    models.BooleanField(
                        blank=True, verbose_name="Наличие бирки на кроссе"
                    ),
                ),
                (
                    "photo_cross",
                    models.ImageField(
                        blank=True,
                        upload_to="photos/%Y/%m/%d/",
                        verbose_name="Фото кросса",
                    ),
                ),
                (
                    "photo_insert",
                    models.ImageField(
                        blank=True,
                        upload_to="photos/%Y/%m/%d/",
                        verbose_name="Фото вкладыша",
                    ),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "ats",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ats.ats",
                        verbose_name="АТС",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кроссы",
                "verbose_name_plural": "Кроссы",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Подразделение")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Подразделения",
                "verbose_name_plural": "Подразделения",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Примечания"),
                ),
                (
                    "cable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ats.cable",
                        verbose_name="Направление КЛС",
                    ),
                ),
                (
                    "cross",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ats.cross",
                        verbose_name="Кросс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Примечания",
                "verbose_name_plural": "Примечания",
            },
        ),
        migrations.AddField(
            model_name="cable",
            name="cross",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ats.cross",
                verbose_name="Кросс",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="department",
            field=models.ManyToManyField(
                related_name="areas", to="ats.department", verbose_name="Подразделение"
            ),
        ),
    ]
