# Generated by Django 4.2 on 2023-06-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cable",
            name="passport",
            field=models.FileField(
                blank=True, upload_to="passports/%Y/%m/%d/", verbose_name="Паспорт КЛС"
            ),
        ),
    ]
