# Generated by Django 4.2 on 2023-05-29 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ats", "0002_alter_area_options_alter_ats_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="cable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ats.cable",
                verbose_name="Направление КЛС",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="cross",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ats.cross",
                verbose_name="Кросс",
            ),
        ),
    ]
